const personTabsTypes = {
  PERSON_TABS_IDENTIFICATES_VALID_REQUEST: "PERSON_TABS_IDENTIFICATES_VALID_REQUEST",
  PERSON_TABS_IDENTIFICATES_VALID_SUCCESS: "PERSON_TABS_IDENTIFICATES_VALID_SUCCESS",
  PERSON_TABS_IDENTIFICATES_VALID_FAILED: "PERSON_TABS_IDENTIFICATES_VALID_FAILED",

  SET_ACTIVE_IDENTIFICATES_TAB: "SET_ACTIVE_IDENTIFICATES_TAB",
  SET_ACTIVE_IDENTIFICATES_RFID_ACTIVE_TAB: "SET_ACTIVE_IDENTIFICATES_RFID_ACTIVE_TAB",
  SET_ACTIVE_IDENTIFICATES_KEENT_ACTIVE_TAB: "SET_ACTIVE_IDENTIFICATES_KEENT_ACTIVE_TAB",
  SET_ACTIVE_IDENTIFICATES_PINCODE_ACTIVE_TAB: "SET_ACTIVE_IDENTIFICATES_PINCODE_ACTIVE_TAB",
  SET_ACTIVE_IDENTIFICATES_BARCODE_ACTIVE_TAB: "SET_ACTIVE_IDENTIFICATES_BARCODE_ACTIVE_TAB",
  SET_ACTIVE_IDENTIFICATES_VIRTUALID_ACTIVE_TAB: "SET_ACTIVE_IDENTIFICATES_VIRTUALID_ACTIVE_TAB",

  SET_TABLE_OF_CARD_LOCATIONS: "SET_TABLE_OF_CARD_LOCATIONS",
  ATTACHE_LOCATIONS_TO_CARD_TYPE: "ATTACHE_LOCATIONS_TO_CARD_TYPE",

  GET_LOCATIONS_REQUEST: "GET_LOCATIONS_REQUEST",
  GET_LOCATIONS_SUCCESS: "GET_LOCATIONS_SUCCESS",
  GET_LOCATIONS_ERROR: "GET_LOCATIONS_ERROR",

  SEARCH_LOCATIONS_REQUEST: "SEARCH_LOCATIONS_REQUEST",
  SEARCH_LOCATIONS_SUCCESS: "SEARCH_LOCATIONS_SUCCESS",
  SEARCH_LOCATIONS_ERROR: "SEARCH_LOCATIONS_ERROR",

  GET_LAND_REQUEST: "GET_LAND_REQUEST",
  GET_LAND_SUCCESS: "GET_LAND_SUCCESS",
  GET_LAND_ERROR: "GET_LAND_ERROR",
};

export default personTabsTypes;
