const userTypes = {
  LOGIN_NEW_USER_REQUEST: "ÄDD_NEW_USER_REQUEST",
  LOGIN_NEW_USER_SUCCESS: "LOGIN_NEW_USER_SUCCESS",
  LOGIN_NEW_USER_FAILED: "LOGIN_NEW_USER_FAILED",

  USER_LOGOUT: "USER_LOGOUT",
};

export default userTypes;
